### ISSUE TITLE
php / non_linearizable / execute before AUTH

### ISSUE THREAD

**Issue by danielebriggi** [sqlitecloud/sdk#10]
See: https://github.com/sqlitecloud/sdk/blob/0945213eb150e9f06db5d44e2c49750b6fc8654b/C/sqcloud.c#L1666

When `non_linearizable=1` then execute the relative command before the `AUTH`

**Comment by marcobambini** [comment]
Please, while working on this add also support for nonlinearizable (alias to non_linearizable)
