### ISSUE TITLE
Where did the SQLite Cloud Bridge go?

### ISSUE THREAD

**Issue by mesterum** [sqlitecloud/sdk#22]
a7b5e483712a56e2443796cae512223ed5e40e30 commit removes the bridge. Is collocated else where? Or it's gone?
[SQLite Bridge](https://docs.sqlitecloud.io/docs/bridge) points nowhere.

**Comment by marcobambini** [comment]
The Bridge was an experimental project and will be replaced by our new offline extension.
In any case you can download it from: https://github.com/sqlitecloud/sdk/tree/93f4a3ded8f9513465778f875429e30dfe15c0a3/SQLiteBridge
