### ISSUE TITLE
HTTP POST Call - Content-Type Charset Error

### ISSUE THREAD

**Issue by drveresh** [sqlitecloud/sdk#32]
While making a POST call to Edge Function with `contentType: "application/json; charset=utf-8"`, it is failing with an error.  Though sometimes it is optional, but if the server is expecting a specific encoding (e.g., UTF-16), then we need to ensure that the contentType header matches that expectation. After removing "charset=utf-8", then it started working. I think its a bug and needs to be fixed.

Code:
```
fetch('https://your-api-endpoint', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json; charset=utf-8'
  },
  body: JSON.stringify({
    key: 'value'
  })
})
```

**Error:**
[2024-08-21 16:24:30 (UTC+05:30) | Error:SQLiteCloudError: no such column: undefined
2024-08-21 16:24:30 (UTC+05:30) | INSERT INTO Table (timestamp,domain,source,status,remarks) VALUES(undefined,'undefined','undefined','undefined','undefined')
2024-08-21 16:24:30 (UTC+05:30) | 1:1:71 no such column: undefined](url)

Also, the errors from your internal system or services are often **not meaningful and appropriate**, and leads to lots of confusions and letting developers debug in different directions and waste lots of time and efforts.

**Comment by gionatamettifogo** [comment]
Hello Veeresh, 

Including charset=UTF-8 in the Content-Type header for "application/json" content type is generally unnecessary and might even cause issues, as was happening in our gateway (which is based on Bun.serve).

According to the RFC 8259 (The JavaScript Object Notation (JSON) Data Interchange Format), JSON text exchanged between systems MUST be encoded using UTF-8. Therefore, specifying the charset is redundant. It would be best not to include it. Everything is processed as UTF-8 (not just in our API but in general in JSON APIs).

The API is tested with "application/json" as the content type and works well. We applied a fix to support charset and suggest not to use charset anyway as it may create issues in proxies and other network components.

See the specs here:
https://datatracker.ietf.org/doc/html/rfc8259#section-8.1

Let me know if I can help further, in that case please reopen the issue.

Best Regards,
Gionata Mettifogo
